version: 2022.{build}-{branch}

image: Visual Studio 2015

environment:

  matrix:

    - PYTHON_VERSION: 3.8
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda37-x64

    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda37-x64

    - PYTHON_VERSION: 3.7
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda37-x64

matrix:

  allow_failures:

    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda37-x64

    - PYTHON_VERSION: 3.7
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda37-x64

install:
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%

  # Install the build and runtime dependencies of the project.
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda create -q -n test-environment python=%PYTHON_VERSION%
  - activate test-environment

  # Check that we have the expected version of Python
  - python --version

  - pip install coveralls PyYAML pytest pytest-cov wheel
  # for hyo2.abc2
  - conda install appdirs bidict cartopy "gdal<3.0.0" matplotlib-base numpy psutil pyproj
  - pip install PySide6
  # for hyo2.soundspeed
  - conda install gsw netCDF4 pillow pyserial scipy
  - pip install https://github.com/hydroffice/hyo2_abc/archive/master.zip

build: off
build_script:
  # --no-deps because of pip not detecting the installed hyo2.abc2
  - pip install --no-deps .
  - conda list --show-channel-urls

test: off
test_script:
  - py.test --cov
  - coverage report -m
  - coveralls

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*
