name: SSM on MacOs

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install appdirs bidict cartopy gdal matplotlib-base numpy psutil pyproj
        conda install gsw netCDF4 pillow pyserial scipy
        pip install PySide2
        pip install https://github.com/hydroffice/hyo2_abc/archive/master.zip
        pip install --no-deps .
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install coveralls PyYAML pytest pytest-cov
        py.test --cov
        coverage report -m
        coveralls
